#!/bin/bash

WORKING_DIR=$1
EXPERIMENT_DIREC="${WORKING_DIR}/SORTED_GROUPS/"
FILE_EXTENSION=$2
SUB_DIRECS=$(ls "$EXPERIMENT_DIREC")

for direc in $SUB_DIRECS
do
    rm ${EXPERIMENT_DIREC}/${direc}/*.${FILE_EXTENSION}
done